### ISSUE TITLE
请问，在dialog存在的情况下，这个snakebar显示在dialog的阴影之下，怎么解决！

### ISSUE THREAD

**Issue by o0o0oo00** [HuanHaiLiuXin/SweetTips#4]

**Comment by o0o0oo00** [comment]
望回复

**Comment by HuanHaiLiuXin** [comment]
Dialog本身是显示在Activity上层的，而Snackbar是向Activity的布局中添加了一个UI控件，所以无法显示在Dialog的上层。

**Comment by HuanHaiLiuXin** [comment]
类似的需求,可以用WindowManager添加View的方法实现,将指定样式的View展示出来.原生是无法实现在Dialog上展示Snackbar的,展示层级导致.
