### ISSUE TITLE
发现华为Android9.0，Demo能显示，但引用进工程却怎么也显示不了的解决方案

### ISSUE THREAD

**Issue by pd2git** [HuanHaiLiuXin/SweetTips#5]
报错Unable to add window android.view.ViewRootImpl$W@6518342 -- permission denied for window type 2009，然而确定已经授权了。后面查了下，官方文档具体如下：

使用 SYSTEM_ALERT_WINDOW 权限的应用无法再使用以下窗口类型来在其他应用和系统窗口上方显示提醒窗口：

TYPE_PHONE
TYPE_PRIORITY_PHONE
TYPE_SYSTEM_ALERT
TYPE_SYSTEM_OVERLAY
TYPE_SYSTEM_ERROR
相反，应用必须使用名为 TYPE_APPLICATION_OVERLAY 的新窗口类型。

使用 TYPE_APPLICATION_OVERLAY 窗口类型显示应用的提醒窗口时，请记住新窗口类型的以下特性：

应用的提醒窗口始终显示在状态栏和输入法等关键系统窗口的下面。
系统可以移动使用 TYPE_APPLICATION_OVERLAY 窗口类型的窗口或调整其大小，以改善屏幕显示效果。
通过打开通知栏，用户可以访问设置来阻止应用显示使用 TYPE_APPLICATION_OVERLAY 窗口类型显示的提醒窗口。
所以在设置type的时候增加判断即可：

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            para.type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
        } else {
            para.type = WindowManager.LayoutParams.TYPE_PHONE;
        }

将判断加到SweetToast.java的initConfiguration(SweetToast sweetToast,int duration)里就可以正常显示了。
定位这个问题花了些时间，这里说下，希望能帮助到有同样问题的伙伴。

**Comment by HuanHaiLiuXin** [comment]
> 报错Unable to add window android.view.ViewRootImpl$W@6518342 -- permission denied for window type 2009，然而确定已经授权了。后面查了下，官方文档具体如下：
> 
> 使用 SYSTEM_ALERT_WINDOW 权限的应用无法再使用以下窗口类型来在其他应用和系统窗口上方显示提醒窗口：
> 
> TYPE_PHONE
> TYPE_PRIORITY_PHONE
> TYPE_SYSTEM_ALERT
> TYPE_SYSTEM_OVERLAY
> TYPE_SYSTEM_ERROR
> 相反，应用必须使用名为 TYPE_APPLICATION_OVERLAY 的新窗口类型。
> 
> 使用 TYPE_APPLICATION_OVERLAY 窗口类型显示应用的提醒窗口时，请记住新窗口类型的以下特性：
> 
> 应用的提醒窗口始终显示在状态栏和输入法等关键系统窗口的下面。
> 系统可以移动使用 TYPE_APPLICATION_OVERLAY 窗口类型的窗口或调整其大小，以改善屏幕显示效果。
> 通过打开通知栏，用户可以访问设置来阻止应用显示使用 TYPE_APPLICATION_OVERLAY 窗口类型显示的提醒窗口。
> 所以在设置type的时候增加判断即可：
> 
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
> para.type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
> } else {
> para.type = WindowManager.LayoutParams.TYPE_PHONE;
> }
> 
> 将判断加到SweetToast.java的initConfiguration(SweetToast sweetToast,int duration)里就可以正常显示了。
> 定位这个问题花了些时间，这里说下，希望能帮助到有同样问题的伙伴。

多谢!这个库时间有点久了,谢谢你这么认真的响应.

**Comment by HuanHaiLiuXin** [comment]
按 https://github.com/pd2git 的意见修复.

**Comment by pd2git** [comment]
不客气，微薄之力，不足挂齿。
开源之心，诸君共勉。
